-- ========================================
-- FIX ORDER_CODE NOT NULL CONSTRAINT
-- ========================================

-- Issue: ORDER_CODE is NOT NULL but trigger generates it AFTER INSERT
-- Solution: Make ORDER_CODE nullable, let trigger fill it

-- Unfortunately SQLite doesn't support ALTER COLUMN
-- We need to recreate the table

BEGIN TRANSACTION;

-- 1. Create new ORDER table with nullable ORDER_CODE
CREATE TABLE IF NOT EXISTS "ORDER_NEW" (
    ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ORDER_CODE TEXT UNIQUE, -- ✅ Removed NOT NULL
    CUSTOMER_ID INTEGER NOT NULL,
    TICKET_TYPE_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL DEFAULT 1,
    UNIT_PRICE INTEGER NOT NULL,
    TOTAL_PRICE INTEGER NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'pending',
    
    PAYMENT_METHOD TEXT DEFAULT 'bank_transfer',
    BANK_NAME TEXT DEFAULT 'ACB',
    BANK_ACCOUNT TEXT DEFAULT '018812398',
    BANK_ACCOUNT_NAME TEXT DEFAULT 'Bảo Tàng Bến Nhà Rồng',
    PAYMENT_REFERENCE TEXT,
    PAYMENT_PROOF_PATH TEXT,
    TRANSACTION_REF TEXT,
    
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAID_AT TIMESTAMP,
    EXPIRES_AT TIMESTAMP,
    
    CONFIRMED_BY INTEGER,
    CONFIRMED_AT TIMESTAMP,
    REJECTION_REASON TEXT,
    
    CUSTOMER_NOTE TEXT,
    ADMIN_NOTE TEXT,
    
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TICKET_TYPE_ID) REFERENCES TICKET_TYPE(TICKET_TYPE_ID),
    FOREIGN KEY (CONFIRMED_BY) REFERENCES USER(USER_ID)
);

-- 2. Copy existing data (if any)
INSERT INTO "ORDER_NEW" SELECT * FROM "ORDER";

-- 3. Drop old table
DROP TABLE "ORDER";

-- 4. Rename new table
ALTER TABLE "ORDER_NEW" RENAME TO "ORDER";

-- 5. Recreate indexes
CREATE INDEX IF NOT EXISTS idx_order_customer ON "ORDER"(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS idx_order_status ON "ORDER"(STATUS);
CREATE INDEX IF NOT EXISTS idx_order_created ON "ORDER"(CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS idx_order_code ON "ORDER"(ORDER_CODE);

-- 6. Recreate trigger
DROP TRIGGER IF EXISTS generate_order_code;

CREATE TRIGGER generate_order_code
AFTER INSERT ON "ORDER"
WHEN NEW.ORDER_CODE IS NULL
BEGIN
    UPDATE "ORDER" 
    SET ORDER_CODE = 'MT' || printf('%06d', NEW.ORDER_ID) || 'DEAD',
        PAYMENT_REFERENCE = 'MT' || printf('%06d', NEW.ORDER_ID) || 'DEAD'
    WHERE ORDER_ID = NEW.ORDER_ID;
END;

-- 7. Recreate other triggers
DROP TRIGGER IF EXISTS update_order_timestamp;

CREATE TRIGGER update_order_timestamp
AFTER UPDATE ON "ORDER"
BEGIN
    UPDATE "ORDER" 
    SET UPDATED_AT = CURRENT_TIMESTAMP
    WHERE ORDER_ID = NEW.ORDER_ID;
END;

DROP TRIGGER IF EXISTS log_order_status_change;

CREATE TRIGGER log_order_status_change
AFTER UPDATE OF STATUS ON "ORDER"
WHEN OLD.STATUS != NEW.STATUS
BEGIN
    INSERT INTO PAYMENT_LOG (ORDER_ID, ACTION, OLD_STATUS, NEW_STATUS, NOTES)
    VALUES (
        NEW.ORDER_ID,
        'status_changed',
        OLD.STATUS,
        NEW.STATUS,
        'Status changed from ' || OLD.STATUS || ' to ' || NEW.STATUS
    );
END;

COMMIT;

-- Test
INSERT INTO "ORDER" (
    CUSTOMER_ID, TICKET_TYPE_ID, QUANTITY, 
    UNIT_PRICE, TOTAL_PRICE, STATUS
) VALUES (1, 1, 1, 20000, 20000, 'pending');

SELECT ORDER_ID, ORDER_CODE, PAYMENT_REFERENCE 
FROM "ORDER" 
ORDER BY ORDER_ID DESC LIMIT 1;
